# Generated by Django 2.2 on 2020-11-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='merchant_details',
            name='merchant_type',
            field=models.CharField(blank=True, choices=[('College', 'College'), ('Institute', 'Institute'), ('Recruiter', 'Recruiter')], max_length=10, null=True),
        ),
    ]
