# Generated by Django 2.2 on 2020-12-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaching',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
