# Generated by Django 3.1.4 on 2020-12-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0002_coaching_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='registration_no',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
