# Generated by Django 2.2 on 2020-11-19 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0001_initial'),
        ('mania', '0002_auto_20201116_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(default='', max_length=15)),
                ('fees', models.CharField(max_length=10)),
                ('registration_id', models.CharField(default='', max_length=100, unique=True)),
                ('txn_id', models.CharField(default='', max_length=100)),
                ('txn_amount', models.CharField(default='', max_length=20)),
                ('txn_date', models.CharField(default='', max_length=50)),
                ('txn_status', models.CharField(default='', max_length=100)),
                ('txn_msg', models.CharField(default='', max_length=400)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mania.Address')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchant_app.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
