# Generated by Django 3.1.6 on 2021-04-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mania', '0002_auto_20210116_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
